config/routes.rb
Rusnak::Application.routes.draw do
  
  resources :posts do
    resources :comments
  end

get '/rover', :to => 'posts#rover'

get '/splash', :to => 'posts#splash'

get '/resume', :to => 'posts#resume'
  
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  has_many :comments
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
  def timePosted_formatted
     timePosted.strftime '%m/%d/%Y'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(params[:comment])
      redirect_to post_path(@post)
    end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @post }
      end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/resume.rb
class ResmueController < ApplicationController
  
  def resume
  end

app/controllers/rover.rb
class RoverController < ApplicationController
  
  def rover
  end

app/controllers/splash.rb
class SplashController < ApplicationController
  
  def splash
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.erb
<div id="footer">

    <p>
      //  Copyright &copy; RyanRusnak.
      <a href="http://www.RyanRusnak.com">//  Ryan Rusnak</a>. 
      <br />//  All Rights Reserved.
      <br />//  For educational purposes only.
    </p>
  </div>

app/views/layouts/_header.erb
<div id="header">
	
	<head>

	</head>

<body>
	
	<ul id="nav">
	<li><a href="/splash">Home</a></li>
	<li><a href="/posts">Projects</a></li>
	<li><a href="/resume">Resume</a></li>
	<li><a href="#">Contact</a></li>
	</ul>
	
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ryan Rusnak</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

</head>
<body>

	<%= render 'layouts/header' %>

	<%= yield %>

	

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for@post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :timePosted %><br />
    <%= f.datetime_select :timePosted %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>

</style>

<script>


</script>

<!--	<input type="range" min="12" max="22" value="12" step="2" id="slider" /><br />
	Value: <input type="text" id="value_display" value="12" />-->

<body>
<div class ="main">
<h1> </h1>
<table class= "post">

<% @posts.each do |post| %>

    <tr><td><h1><b><%= post.title %></b></h1></td></tr>
    <tr><td><h3>Posted: <%= post.timePosted_formatted %></h3></td></tr>
    <tr><td><%= image_tag post.photo.url(:small) %></td></tr>
    <tr><td><%= post.body %></td></tr>
    <tr><td><%= link_to 'Show', post %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete%></tr>
<% end %>
</table>


<br />

<%= link_to 'New Post', new_post_path %>



<div id="sideMenu">
<ul>
	<li><a href="<?php echo get_settings('home'); ?>">HOME</a></li>
	<li><a href="wordpress/recipes/">RECIPES</a></li>
	<li><a href="wordpress/travel/">TRAVEL</a></li>
	<li><a href="http://www.wordpress.org">WORDPRESS</a></li>
</ul>
</div>


</div>
</body>
<%= render 'layouts/footer' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/resume.html.erb
<a title="View Resume on Scribd" href="http://www.scribd.com/doc/65460888/Resume" style="margin: 12px auto 6px auto; font-family: Helvetica,Arial,Sans-serif; font-style: normal; font-variant: normal; font-weight: normal; font-size: 14px; line-height: normal; font-size-adjust: none; font-stretch: normal; -x-system-font: none; display: block; text-decoration: underline;">Resume</a><iframe class="scribd_iframe_embed" src="http://www.scribd.com/embeds/65460888/content?start_page=1&view_mode=list&access_key=key-1n9630rbgfa9fzjmxtwb" data-auto-height="true" data-aspect-ratio="0.772727272727273" scrolling="no" id="doc_14629" width="100%" height="600" frameborder="0"></iframe><script type="text/javascript">(function() { var scribd = document.createElement("script"); scribd.type = "text/javascript"; scribd.async = true; scribd.src = "http://www.scribd.com/javascripts/embed_code/inject.js"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(scribd, s); })();</script>

app/views/posts/rover.html.erb
<style type="text/css">

<!--
#container{
    width:650px;
    height:500px;
    border:1px solid #000;
    overflow:hidden;
 
}
#container iframe {
    width:900px;
    height:800px;
    margin-left:-125px;
    margin-top:-140px;
    border:0 solid;
 }
 #target{
     position: absolute;
     top: 0px;
     left: 0px;
    
}

-->
</style>


        <div id="container">
<iframe src="http://192.168.1.115/img/main.cgi?next_file=main.htm" scrolling="no"></iframe>
</div> 

<!-- ><div id="target">
           <img src="images/target.png" width="300" height="320"/><br />
</div>-->

<script type="text/javascript">document.write(unescape("%3Cscript src='" + "http://www.iobridge.com/widgets/io.js?u3jBQGnQsaru' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">document.write(unescape("%3Cscript src='" + "http://www.iobridge.com/widgets/io.js?MpnLBkAksCPc' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">document.write(unescape("%3Cscript src='" + "http://www.iobridge.com/widgets/io.js?chFuYSApFfiz' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">document.write(unescape("%3Cscript src='" + "http://www.iobridge.com/widgets/io.js?WANOrloCNbFG' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">document.write(unescape("%3Cscript src='" + "http://www.iobridge.com/widgets/io.js?0W5zd4QR5OvD' type='text/javascript'%3E%3C/script%3E"));</script>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Timeposted:</b>
  <%= @post.timePosted %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @post.photo.url(:small) %>
</p>

<p>
  <b>Body:</b>
  <%=h @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <b>Name:</b>
    <%= comment.name %>
  </p>
 
  <p>
    <b>Body:</b>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/splash.html.erb
<body>
<div class="splashTitle">
	<b>The facts</b>
	</div>
	
<div class="splashAbout">
<b>about</b>
	</div>
	
<div class="splashName">
	<b>ryan rusnak</b>
	</div>
	
<div class="columnOne">
	<b>This is the personal <del>blog</del> <del>portfolio</del> website of Ryan Rusnak</b>
	</div>
	
<div class="columnOneText">
	<MULTICOL COLS=2>
	Currently a student at Carnegie Mellon University, Ryan is studying Human Computer Interaction
	and is slowly plotting his world take over using a combination of Ruby on Rails, iOS development 
	and bridging the gap between physical objects and the internet. 
	</MULTICOL>
	</div>
	</body>